---
include:
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_sofle_studio_left
  - board: eyelash_sofle_left
    shield: settings_reset
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view_battery  # updated entry
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view_battery # updated entry


